version: "2"

services:
  editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8080:8080"

  ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8081:8080"
    volumes:
      - ./swagger.yml:/usr/share/nginx/html/swagger.yml
    environment:
      API_URL: swagger.yml

  redoc:
    image: redocly/redoc
    ports:
      - 8082:80
    volumes:
      - ./swagger.yml:/usr/share/nginx/html/swagger.yml
    environment:
      SPEC_URL: swagger.yml
